### ISSUE TITLE
 Error in NAN check after PROFX:compute_pressure

### ISSUE THREAD

**Issue by iancrossfield** [exoclime/THOR#14] opened 2020-04-30 21:55 UTC
After installing THOR (Ubuntu 18.04, compute power=3 NVIDIA GPU), most of the test cases in 'ifile' fail (after some successful initialization) with:

...
>  Physics module: empty   
>    ********** 
>    ********** 
> 
>     
>  Simulation
>    Start from rest = true 
>    Output directory = earth_hs 
>    Start output numbering at 0.
>  Starting the model integration.
> 
> 
>  Time step number = 1/103680 || Time = 0.011574 days. 
> 	 Elapsed 7s || Left: 8d 18h 37m 53s || Completion: 2020-05-09 11:30:19. 
> 
>  Error in NAN check after PROFX:compute_pressure!

However, the "earth_sync" case runs through at least the first several hundred steps... I'll keep looking into this, but it's odd that the 'out-of-the-box' examples should crash. Thanks for any insights!

**Comment by iancrossfield** [comment] 2020-05-01 16:35
After a bit more debugging, the error flag `check_h' in `profx_driver.cu' seems to be set to `True' at this line:    
> cudaMemcpy(&check_h,` check_d, sizeof(bool), cudaMemcpyDeviceToHost);

For the earth_sync case (the only one that doesn't crash; still chugging along) I see that check_d=13475328, while for the crashing cases we have check_d=13999616 for shallowhj  (or check_d=14392832 for deephj, or check_d=9429504 for earth_hstest).  No clear hints here, though I'm a bit out of my depth with the GPU coding. Thoughts/suggestions?

**Comment by nabajour** [comment] 2020-05-01 16:44
What version are you running? dev or master ? One of the releases from the release page ? 

And what GPU are you running this on ?

**Comment by iancrossfield** [comment] 2020-05-01 16:54
Thanks @nabajour ! Answers below:

Version: It's the latest set from the GitHub page and the Master repo (as of earlier this week).  The file thor_driver.cu and most of the files in /src/ESP/ claim this is version 2.0:
> 2.0     30/11/2018 Released version (RD & US)

Where is "the release page," and is there a particular version I should be using?

I'm testing this on Quadro K1100M (compute power=3.0) since I'm mostly confined to home.
As for the CUDA version:
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:24:38_PDT_2019
> Cuda compilation tools, release 10.2, V10.2.89

I've attached a logfile for the shallow Hot Jupiter case (since that's the sort of system I'm most interested in).

[esp_log_shallow.log](https://github.com/exoclime/THOR/files/4565341/esp_log_shallow.log)

**Comment by nabajour** [comment] 2020-05-01 17:50
HEAD of `master` branch should be OK. 

We develop on `dev` and from time to time synchronise to `master`. And at some points when we have new features or bugfixes, we mark versions as point release in the [release page](https://github.com/exoclime/THOR/releases). 

Current `master` works correctly here, whereas from your log, it fails at the first step ?

One difference I see is that you have compute power = 3.0. I tested THOR on 3.5 (K20), 6.1 (gtx 1080), 7.5 (RTX 2080). I don't have a machine with compute power = 3.0 to test at hand, to see if it's related to that. I'll need to research if this can be an issue.

Do you have access to another machine to make a quick check if it's related to the hardware support ?

**Comment by iancrossfield** [comment] 2020-05-01 19:26
I'll hunt around for a higher-powered system.  It's odd, though, that the earth_sync case still runs successfully (see attached log). Could there be some fundamental difference between that test and all the others?
Many thanks!
[esp_log_Earth.log](https://github.com/exoclime/THOR/files/4566000/esp_log_Earth.log)

**Comment by deitrr** [comment] 2020-05-04 08:34
Hi @iancrossfield,

Thanks for checking out the code, and for reporting the issue! 

Like @nabajour, I am not able to reproduce the issue. It looks to me like it should be an issue either with this GPU, with compilation, or a conflict between library versions. But if that were the case, I'd expect all the simulations to fail, including the earth_sync case. It is very strange. There's nothing unique about this case that would allow it to work when the others fail. 

One thing I noticed is the line "Physics module: empty" in your log files. I realized also, after checking our wiki, that we neglected to explain one step, apologies for that. After you create the file "Makefile.conf" (the file where you can set the SM/compute capability), you should also change the line "MODULES_SRC := src/physics/managers/empty/" to "MODULES_SRC := src/physics/managers/multi/". This couples the double gray radiative transfer module and a few other things that are needed for the "earth_rt_dc_g5" and "wasp43b_ex" cases. I could've sworn we put that in the wiki somewhere, but I don't see it now... 

Just to double check, for my sanity, in the "Makefile.conf" file, you have "SM:=30"? In my experience, the code should fail completely if this is set incorrectly, but I just wanted to make sure we aren't encountering some weird loophole where it still tries to run if the SM is wrong.

One thing that might be helpful for us is if you could run "make clean", then recompile ("make release") and copy the compilation output into a file and attach it here. Just to see if there's anything unusual during compilation.

Hopefully we can get this ironed out quickly.

**Comment by iancrossfield** [comment] 2020-05-04 15:47
Hi @deitrr - thanks for your suggestions.  I verified that I have SM:=30 in my Makefile, I switched to the 'multi' physics module, I did 'make clean', and then 'make release' (see attached compile.log).  

Curiously, after this even the earth_sync.thr case crashes with the same error ("Error in NAN check after PROFX:compute_pressure!").  The only difference seems to be whether I 'make release' or 'make -j8 release'.  If I do the latter, the earth_sync case runs but all others crash -- if I just do 'make release', all cases crash (with the same error).

[compile.log](https://github.com/exoclime/THOR/files/4575638/compile.log)

**Comment by deitrr** [comment] 2020-05-05 14:18
Thanks @iancrossfield ! This is really helpful. The behavior with/without the -j8 flag is really strange. At the moment, we are somewhat baffled. Stay tuned--we are doing some research and will hopefully find a way to test on a similar GPU soon.

**Comment by deitrr** [comment] 2020-05-08 09:26
Hi @iancrossfield, 

Yesterday, @nabajour was able to reproduce the error using an older GPU--at least, we think it is the same error. He traced it back to some badly initialized arrays (a mistake courtesy of yours truly). What happens then, it seems, is that on newer GPUs, the arrays end up filled with zeros (as they should be), but on some older devices the arrays can sometimes be filled with random large numbers. This naturally causes the code to crash in a somewhat inconsistent pattern, depending on the state of the computer and the initial conditions. And we never noticed the issue because it only happens on some devices! Pretty sneaky bug. :)

I've pushed a fix that solves the bug I described above--I hope that it is indeed the cause of the issue you are experiencing. Can you pull the latest version from the master branch and test on your machine?

In any case, HUGE thanks for helping us discover a bug!

**Comment by iancrossfield** [comment] 2020-05-08 15:15
I confirm that with the updated code, the cases now run successfully. (At least, for the first few dozen steps -- on such a low-powered system one sim will take ~10 days to run).  Thanks very much for tracking this down! I look forward to playing more with THOR and seeing what it can do.

**Comment by iancrossfield** [comment] 2020-05-09 17:29
@nabajour @deitrr -- Just a follow-up question: now that I've gotten this running I'm considering whether it's worth getting a better GPU (or a few!). Do you all mainly run THOR in cluster environments, or do you sometimes run it on a single, standalone machine? And if the latter: do you have any sort of rough feel for how GPU "compute power" (and/or # of GPUs) affects the overall runtime of a THOR simulation?

**Comment by deitrr** [comment] 2020-05-11 08:16
In answer to your first question: it varies a bit. For development, debugging, and shorter simulations (< 1 day), I often run the code on my local machine (compute power 6.1). For longer simulations, I generally run on a cluster, primarily because we have a number of GPUs available there and I can submit several jobs and have them managed by a job scheduler. For the most part, the cluster GPUs I am using are gaming cards with compute power 6.1 or 7.5. The 1200 day shallow hot jupiter case runs in about 1.5 hours on the compute power 7.5 GPUs (Geforce RTX 2080 Ti), if that gives you something to compare with. The Held-Suarez test I usually run at a step up in resolution (4x as many operations), and that takes about 3.5 hours on the same GPU.

Compute power isn't the only thing to consider, however. The gaming cards, like the Geforce series, are much cheaper than the professional cards, but are slower at double-precision operations. @jmmendonca has been running THOR on some newer professional cards (the Volta series, I think) and can run some simulations in less than an hour! I don't have much experience with the professional cards, personally, so I can't give you any hard figures, but it may be worth asking @sigrimm or @jmmendonca about them if you are curious.

Currently THOR only runs on a single GPU. It is a long-term goal to enable the code to run on multiple cards, but it is a significant coding change, so it will be some time before we get there. This, unfortunately, puts a limit on the resolution of the simulations we can run--we are limited by the amount of available GPU memory. So that is the last thing to consider--how much memory is available on the card. On the Geforce GTX 1080 Ti, we can go to a horizontal resolution of ~1 deg. On the 2080s, we can do a little better, down to ~0.5 deg. To go finer in resolution than that, we will need GPUs with more memory or the upgrade to multiple GPUs. 

Hopefully that gives you a rough sense of the important things.

**Closed by deitrr** 2020-05-11 08:16 UTC

**Comment by iancrossfield** [comment] 2020-06-17 22:09
I hate to bring this issue up, but it's reared its head again. I can run all the benchmark tests successfully, and most finish in just 3-4 hours on my GeF. 2080 RTX Ti.  

I've tried adapting the "wasp43" benchmark case for some other planets, but with mixed results. At least for the simulation I'm trying (see attached THR file) the simulation will run to completion if `Top_altitude = 4.0e6` (corresponding to ~30 mbar), but if I extend the simulation higher up (e.g. to 8.0e6) to probe higher altitudes/lower pressures, I get the old `Error in NAN check after PROFX:compute_pressure!` after a few hundred steps. I've attached the log file.

Any thoughts? Thanks!

[fail.log](https://github.com/exoclime/THOR/files/4795303/fail.log)

[ltt9779bVanillaV3.thr.txt](https://github.com/exoclime/THOR/files/4795295/ltt9779bVanillaV3.thr.txt)

**Comment by deitrr** [comment] 2020-06-18 08:49
Hi @iancrossfield!

Thanks for the update. Unfortunately, from what you are describing, you may be running into one of the fundamental limitations of the model (and GCMs in general). 

In Thor, we tend to be limited to absolute pressures above ~ 10^-6 or 10^-7 bar. There are a number of long-term solutions that we've discussed in the group--the problem is that all involve a substantial reworking of the code, so it will be some time before we get there. 

For hot Jupiters, the problem can be particularly challenging because of the day/night dichotomy. If you are reaching 10^-6 bar in the coolest regions, you may only be probing 10^-3 bar at the sub-stellar point! GCMs that use a pressure coordinate are often able to circumvent the issue, but  have other issues of their own. There doesn't seem to be, yet, a perfect model for these planets. 

Just to be certain that this is the case, there's a few ways you can check the minimum pressure you are reaching: 
1) Run the "TP" option of the mjolnir plot script on the last step you are reaching. This will plot a subset of temperature-pressure profiles, from which you can estimate the lowest pressures reached. You'll need to set the n_out option to the final step you're reaching (step 108 in the log file you attached) so that an output file is produced before the crash. 
2) Pull the latest version from the dev branch, and re-run the simulation. We are now outputting the minimum pressure to screen on every step, so you can see directly what the lowest pressure is. This is probably the simpler way.

In the short-term, there are a few tricks you can try to extend the domain to lower pressures (note that I have had limited success with these).  
1) As you found, decreasing the time step may help. The radiative time scale is often a good estimate for this: t_rad ~ Cp * P / (4 * \sigma * g * T^3). However, since you won't know the temperature and pressure at the top of the model before actually running the model, it requires a bit of trial and error. 
2) Try initializing from Guillot profiles instead of isothermal (not sure if that's what you're doing now or not). In the config file, change "init_PT_profile" from "isothermal" to "guillot". I have found the model to usually be more stable with this setting.
3) Adjust the sponge layer parameters (ns_ray_sponge, Ruv_sponge, Rw_sponge, etc). There are no strict rules for how to do this--it is largely a process of trial and error. The sponge layer, if you aren't already familiar with this, is used to try to damp the reflection of gravity waves off the upper boundary, which tend to amplify and break, creating steep gradients that then lead to numerical instabilities. Dealing with the upper boundary is a persistent problem in GCMs...

Anyway, I hope that helps!
